#spring:
#  application:
#    name: chat-server
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/sever-app
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
server:
  port: 8080
socket:
  host: 0.0.0.0
  port: 8878
